Added dev test Added inject Clean up lazass Added String Manipulation Added Lighttpd restart

diff --git a/lib/lazass b/lib/lazass
--- a/lib/lazass
+++ b/lib/lazass
@@ -1,114 +1,29 @@
-##! LAZASS LIBRARY 1.7
-##* Description: Library for installation/configuration scripts
-##* Author:Sarrailh Remi   
-##* License:http://www.tldrlegal.com/l/Gplv3
-###****
-VER="1.7"
+## LAZASS LIBRARY ##
+###############################################################
+## Description: Library for scripts                           #
+## Author:Sarrailh Remi                                       #
+## License:http://www.tldrlegal.com/l/Gplv3                   #
+## Manual:http://madnerd.org/Create_Scripts_with_Lazass       #
+###############################################################
+VER="2"
 AUTHOR="Sarrailh Remi"
 LICENSE="Gplv3"
-###################
-##!! DISPLAY FUNCTIONS
-#########################################################
-##> These functions display text without doing nothing else
-#########################################################
 
-###############
-##!!! COLOR    
-###############
-OK="\\033[1;32m"      ##* $OK      -> GREEN
-NORMAL="\\033[0;39m"  ##* $NORMAL  -> WHITE
-ERR="\\033[1;31m"     ##* $ERR     -> RED
-INFO="\\033[1;34m"    ##* $INFO    -> BLUE
-WARN="\\033[1;33m"    ##* $WARN    -> YELLOW
-PICOLOR="\\033[1;35m" ##* $PICOLOR ->PINK
+OK="\\033[1;32m"
+NORMAL="\\033[0;39m"
+ERR="\\033[1;31m"
+INFO="\\033[1;34m"
+WARN="\\033[1;33m"
+PICOLOR="\\033[1;35m"
+## VARIABLES ##
 
 ##############
-##!!! TEXT    
+## DISPLAY   #
 ##############
-#>* $1 TEXT
-#>* $2 COLOR (optional)
 
-##!!!! nlbecho() : Text with no line break
-nlbecho() {
-echo -ne $2
-echo -ne "$1 "
-echo -ne $NORMAL
-}
+# HEADER #
 
-##!!!! colecho() : Colored text
-colecho() {
-echo -ne $2
-echo $1
-echo -ne $NORMAL
-}
-
-##!!!! listecho() : Make a List item with ->
-listecho() {
-	nlbecho "->" $OK 
-	echo $1
-}
-
-##########################
-##!!! INFORMATION MINIBOX
-##########################
-
-##!!!! ok() : GREEN [OK]
-function ok() {
-	echo -ne " ["
-	echo -ne $OK
-	echo -ne "OK"
-	echo -ne $NORMAL
-	echo "]"
-}
-
-##!!!! skip() BLUE [SKIPPED]
-function skip() {
-	echo -ne " ["
-	echo -ne $INFO
-	echo -ne "SKIPPED"
-	echo -ne $NORMAL
-	echo "]"
-}
-
-##!!!! warning() YELLOW [WARNING]
-function warning() {
-	echo -ne " ["
-	echo -ne $WARN
-	echo -ne "WARNING"
-	echo -ne $NORMAL
-	echo "]"
-}
-
-##!!!! error() RED [ERROR]
-function error() {
-	echo -ne " ["
-	echo -ne $ERR
-	echo -ne "ERROR"
-	echo -ne $NORMAL
-	echo "]"
-}
-
-#################
-##!!! LINE BREAK 
-#################
-
-##!!!! jumpline() Simple Line break
-jumpline() {
-	echo ""
-}
-
-##!!!! line_break() Line break with a line
-line_break() {
-	echo -e $INFO"____________________________________"
-	echo -e $NORMAL
-}
-
-#########
-##!!!  BOX
-#########
-#>* $1 TEXT
-
-##!!!! description() : Create a description box, Use it to describe your SCRIPT
+# Create a description box, Use it to describe your SCRIPT
 description() {
 	echo -ne $WARN 
 	echo "LAZASS INSTALL $VER by $AUTHOR - $LICENSE"
@@ -120,31 +35,107 @@ description() {
 	echo -ne $NORMAL
 }
 
-##!!!! messagebox() : Create a messagebox, Use it to describe an ACTION
+# Create a messagebox, Use it to describe an ACTION
 messagebox() { 
 echo -e $INFO"____________________________________"
 echo $1
 line_break
 }
 
-##!!!! error_box() : Create an error box to show an CRITICAL ERROR
-##>* $1 TEXT/ERROR CODE
+# Create an error box to show an CRITICAL ERROR
+#$1 : TEXT/ERROR CODE
 error_box() {
 	echo -ne $ERR
 	echo "--- ERROR CODE: $1 ---"
 	echo -ne $NORMAL
 }
 
-##!!!! console() Create a console box use it to show COMMAND OUTPUT
+# Create a console box use it to show COMMAND OUTPUT
 console() {
 	echo -ne $OK
 	echo "/////////////////////"
 	echo -ne $NORMAL
 }
 
+display_gpio() {
+	line_break
+	echo "5V  5V  GND 15  16  1   GND 4   5   GND 6   10  11 "
+    echo "o   o   o   o   o   o   o   o   o   o   o   o   o  "
+    echo "o   o   o   o   o   o   o   o   o   o   o   o   o  "
+    echo "3V  8   9   7   GND 0   2   3   3V  12  13  14  GND"
+    colecho "P1" $OK
+    line_break
+}
+
+# TEXT #
+
+# Colored text
+colecho() {
+echo -ne $2
+echo $1
+echo -ne $NORMAL
+}
+
+# Text with no line break
+nlbecho() {
+echo -ne $2
+echo -ne "$1 "
+echo -ne $NORMAL
+}
+
+# Make a List item with ->
+listecho() {
+	nlbecho "->" $OK 
+	echo $1
+}
+
+#Mini Boxes 
+
+ok() {
+	echo -ne " ["
+	echo -ne $OK
+	echo -ne "OK"
+	echo -ne $NORMAL
+	echo "]"
+}
+
+skip() {
+	echo -ne " ["
+	echo -ne $INFO
+	echo -ne "SKIPPED"
+	echo -ne $NORMAL
+	echo "]"
+}
+
+warning() {
+	echo -ne " ["
+	echo -ne $WARN
+	echo -ne "WARNING"
+	echo -ne $NORMAL
+	echo "]"
+}
+
+error() {
+	echo -ne " ["
+	echo -ne $ERR
+	echo -ne "ERROR"
+	echo -ne $NORMAL
+	echo "]"
+}
+
+#Line Break
+
+jumpline() {
+	echo ""
+}
+
+line_break() {
+	echo -e $INFO"____________________________________"
+	echo -e $NORMAL
+}
 
 ##!!!! thank() : Thanks message, use it at the END OF SCRIPT
-function thank () {
+thank () {
 	if [[ $noreset != 1 ]]
 	then
 	echo ""
@@ -153,19 +144,15 @@ function thank () {
 	echo "Have fun and Happy Hacking !"
 	echo "----------------------------"
 	echo -ne $NORMAL
-	read
 	exit 0
 	fi
 }
 
+##############
+## DATAS     #
+##############
 
-###################
-##!! ERRORS HANDLER 
-#################################################
-##> Theses functions handles errors          
-#################################################
-
-##!!!! verify_root() : Verify if you have root permissions
+#Verify if you have root permissions
 verify_root() {
 	if [ $(id -u) -ne 0 ]; then
 		error_box
@@ -178,7 +165,271 @@ verify_root() {
 	fi
 }
 
-##!!!! aptget_error() : Handle APT error (launched when using installer)
+#Return First IP
+firstip() {
+nlbecho $(hostname -I |cut -f1 -d' ') $RED
+}
+
+#Return List all ip
+ip_list() {
+nlbecho $(hostname -I) $RED
+}
+
+#Return List Samba name and if it failed show first ip
+smb_getname() {
+	if [[ -f /etc/samba/smb.conf ]]
+	then
+		smbname=$(cat /etc/samba/smb.conf |grep "netbios name = ")
+		if [[ $? == 0 ]]
+			then	
+			echo $smbname|sed 's/netbios name = //'
+			else
+			firstip
+		fi
+	else
+	firstip
+	fi
+}
+
+#Ping a website and tell if you are (it is) online or not
+#$1: address to ping
+ping_test() {
+	messagebox "INTERNET CONNECTIVITY"
+	console
+	ping -c1 $1 && internet=1 || internet=0
+	console
+	if [[ $internet == 1 ]]
+	then
+	echo -ne "INTERNET"
+	ok
+	else
+	echo -ne "INTERNET"
+	error
+	echo -ne $ERR
+	echo "NO INTERNET CONNECTIVITY DETECTED SCRIPT STOPPED"
+	echo -ne $NORMAL
+	exit 1
+	fi
+}
+
+##########################
+## STRING MANIPULATION   #
+##########################
+
+#Erase from string to string
+#$1: File to read
+#$2: First String
+#$3: Last String
+erasefromto() {
+	cat $1|sed -e "/$2/,/$3/d"
+}
+
+##Erase string
+#$1: File to read
+#$2: String
+erasestring() {
+	cat $1|sed "s/$2//"
+}
+
+#Extract text from file
+#$1: File to read
+#$2: First String
+#$3: Last String
+extractfromto() {
+	sed -n "/^$2\(\)/,/^$3/p" $1
+}
+
+#Extract a function from a bash script
+#$1: File to read
+#$2: Function name
+extractfunction() {
+sed -n "/^$2()\(\)/,/^}/p" $1
+}
+
+#Search a string in file
+#$1: File to read
+#$2: String to search
+#return $found: 0:true 1:false
+searchstring() {
+	found=""
+	cat $1 |grep -q $2
+	found=$?
+	if [ $found == 0 ]
+		then
+		listecho "$2 founded"
+	fi
+}
+
+##############
+## ACTIONS   #
+##############
+
+#Launch a script insides LAZASS
+launchscript() {
+	export noreset=1
+	"scripts/$1"
+	error_launchscript=$?
+	if [[ $error_launchscript != 0 ]]
+		then
+		error_box $error_launchscript
+		echo "Cannot launch scripts/$1"
+		error_box $error_launchscript
+		exit 0
+	fi
+}
+
+#Update APT
+updater() {
+	ping_test "google.com"
+	messagebox "Update Package"
+	console
+	apt-get update
+	aptget_error $?
+	console
+}
+
+#Install a packet (with error handling)
+#$1 package (apt-get install package)
+installer() {
+	messagebox "INSTALL: $1"
+	dpkg -s "$1"|grep "Status: install ok installed" > /dev/null 2>&1
+#IS THE PACKAGE ALREADY INSTALLED ?
+	if [[ $? == 1 ]]
+		then
+		console
+		apt-get install "$1"
+		aptget_error $?
+		console
+		dpkg -s "$1"|grep "Status: install ok installed" > /dev/null 2>&1
+#WAS THE PACKAGE INSTALLED ?
+		if [[ $? == 0 ]]
+		then
+			echo -ne "RESULT: $1"
+			ok
+		else
+			echo -ne "RESULT: $1"
+			error
+			read
+		fi
+	else
+		echo -ne "RESULT: $1"
+		skip
+	fi
+}
+
+#Restart a service
+#$1 servive (as in /etc/init.d)
+restarter() {
+	messagebox "Restarting $1"
+	console
+	service $1 restart
+	console
+}
+
+#create_dir() : Make a directory (recursively)
+#$1 Name of the directory 
+createdir() {
+messagebox "Create directory $1"
+if [ -d "$directory" ]
+then
+nlbecho "CREATE DIRECTORY $directory"
+skip
+else
+mkdir -p $1
+	if [[ $? == 0 ]]
+		then
+		nlbecho "CREATE DIRECTORY"
+		ok
+		else
+		error_box $?
+		echo "CANNOT CREATE DIRECTORY"
+		error_box " "
+		exit 0
+	fi
+fi
+}
+
+#Git Cloner
+#$1 Program name (for showing it)
+#$2 Repo url (ex: http://github.com/nameofuser/nameofrepo)
+#$3 Name of the directory where the repo will be cloned
+#If the directory exists try to update it
+gitcloner() {
+messagebox "Clone $1"
+console
+git clone $2 $3
+giterror=$?
+console
+if [[ $giterror == 128 ]]
+	then
+	nlbecho "ALREADY CLONED"
+	skip
+	messagebox "Update $1"
+	cd $3
+	git pull
+	cd $path_lazass
+fi
+}
+
+##############
+## PROMPT    #
+##############
+
+#Ask if the user want to continue the script
+continue_prompt() {
+	read -r -p "Continue? [Y/n] " response
+			case $response in
+				[yY])
+				echo "Resuming..."
+				;;
+				*)
+				echo ""
+				colecho "Installation stopped" $info
+				echo -ne $NORMAL
+				exit 0
+				;;
+			esac
+}
+
+#Prompt to create a directory
+createdir_prompt() {
+read -r -p "Path [ex:/home/pi/]: " directory
+jumpline
+nlbecho "This will create"
+colecho "$directory" $ERR
+read -r -p "CONFIRM [Y/n/a] [Yes/No/Abort] : " confirmation
+case $confirmation in
+				[yY])
+				createdir $directory
+				;;
+				[aA])
+				error_box 1
+				echo "INSTALLATION ABORTED"
+				error_box 1
+				exit 0
+				;;
+				*)
+				jumpline
+				createdir_prompt
+				;;
+esac
+}
+
+#Prompt to create a backup of a file
+#$1 File to backup
+backup_prompt(){
+colecho "THIS WILL OVERWRITE $1 !" $ERR
+colecho "(A backup will be made at $1.backup.TIMESTAMP)" $WARN
+continue_prompt
+TIMESTAMP=$(date +%y%m%d)'_'$(date +%H%M%S)
+cp $1 $1'.backup.'$TIMESTAMP
+}
+
+#################
+## DEPENDANCIES #
+#################
+
+#Handle APT error (launched when using installer)
 aptget_error() {
 	apterror=$1
 	case $apterror in 
@@ -204,7 +455,6 @@ aptget_error() {
 				echo "INSTALLATION FAILED!!!"
 				echo "You should fixed APT-GET MANUALLY BEFORE RETRY"
 				error_box $apterror
-				read
 				exit 0
 				;;
 			esac
@@ -218,7 +468,6 @@ aptget_error() {
 		echo "Installation Aborted !"
 		error_box $apterror
 		echo -ne $NORMAL
-		read
 		exit 0
 		;;
 			
@@ -239,242 +488,12 @@ aptget_error() {
 		
 }
 
-#########################
-##!! Get Infos         
-###########################################
-##> Get informations from the system      
-###########################################
-
-##!!!! firstip() : Return First IP
-firstip() {
-nlbecho $(hostname -I |cut -f1 -d' ') $RED
-}
-
-##!!!! ip_list() : Return List all ip
-ip_list() {
-nlbecho $(hostname -I) $RED
-}
-
-##!!!! smb_getname() : Return List Samba name and if it failed show first ip
-smb_getname() {
-	if [[ -f /etc/samba/smb.conf ]]
-	then
-		smbname=$(cat /etc/samba/smb.conf |grep "netbios name = ")
-		if [[ $? == 0 ]]
-			then	
-			echo $smbname|sed 's/netbios name = //'
-			else
-			firstip
-		fi
-	else
-	firstip
-	fi
-}
-
-
-
-##!!!! pint_test() : Ping a website and tell if you are (it is) online or not
-##>* $1: address to ping
-ping_test() {
-	messagebox "INTERNET CONNECTIVITY"
-	console
-	ping -c1 $1 && internet=1 || internet=0
-	console
-	if [[ $internet == 1 ]]
-	then
-	echo -ne "INTERNET"
-	ok
-	else
-	echo -ne "INTERNET"
-	error
-	echo -ne $ERR
-	echo "NO INTERNET CONNECTIVITY DETECTED SCRIPT STOPPED"
-	echo -ne $NORMAL
-	read
-	exit 1
-	fi
-}
-
-#######################
-##!! Actions functions
-#############################################
-##> This functions performs complex actions  
-#############################################
-
-#########################
-##!!! UNATTENDED ACTIONS  
-#########################
-
-##!!!! launcscript() : Launch a script insides LAZASS
-launchscript() {
-	export noreset=1
-	"scripts/$1"
-	error_launchscript=$?
-	if [[ $error_launchscript != 0 ]]
-		then
-		error_box $error_launchscript
-		echo "Cannot launch scripts/$1"
-		error_box $error_launchscript
-		read
-		exit 0
-	fi
-}
-
-##!!!! updater() : Update APT
-updater() {
-	ping_test "google.com"
-	messagebox "Update Package"
-	console
-	apt-get update
-	aptget_error $?
-	console
-}
-
-##!!!! installer() Install a packet (with error handling)
-##>* $1 package (apt-get install package)
-installer() {
-	messagebox "INSTALL: $1"
-	dpkg -s "$1"|grep "Status: install ok installed" > /dev/null 2>&1
-	#IS THE PACKAGE ALREADY INSTALLED ?
-	if [[ $? == 1 ]]
-		then
-		console
-		apt-get install "$1"
-		aptget_error $?
-		console
-		dpkg -s "$1"|grep "Status: install ok installed" > /dev/null 2>&1
-		#WAS THE PACKAGE INSTALLED ?
-		if [[ $? == 0 ]]
-		then
-			echo -ne "RESULT: $1"
-			ok
-		else
-			echo -ne "RESULT: $1"
-			error
-			read
-		fi
-	else
-		echo -ne "RESULT: $1"
-		skip
-	fi
-}
-
-##!!!! restarter() : Restart a service
-##>* $1 servive (as in /etc/init.d)
-restarter() {
-	messagebox "Restarting $1"
-	console
-	service $1 restart
-	console
-}
-
-##!!!! create_dir() : Make a directory (recursively)
-##>* $1 Name of the directory 
-createdir() {
-messagebox "Create directory $1"
-if [ -d "$directory" ]
-then
-nlbecho "CREATE DIRECTORY $directory"
-skip
-else
-mkdir -p $1
-	if [[ $? == 0 ]]
-		then
-		nlbecho "CREATE DIRECTORY"
-		ok
-		else
-		error_box $?
-		echo "CANNOT CREATE DIRECTORY"
-		error_box " "
-		read
-		exit 0
-	fi
-fi
-}
-
-##!!!! gitcloner() : Git Cloner
-##>* $1 Program name (for showing it)
-##>* $2 Repo url (ex: http://github.com/nameofuser/nameofrepo)
-##>* $3 Name of the directory where the repo will be cloned
-##>* If the directory exists try to update it
-gitcloner() {
-messagebox "Clone $1"
-console
-git clone $2 $3
-giterror=$?
-console
-if [[ $giterror == 128 ]]
-	then
-	nlbecho "ALREADY CLONED"
-	skip
-	messagebox "Update $1"
-	cd $3
-	git pull
-	cd $path_lazass
-fi
-}
-
-#########################
-##!!! INTERACTIVE ACTIONS
-#########################
-
-##!!!! continue_prompt() : Ask if the user want to continue the script
-##> AVOID USING IT (see issue 1)
-continue_prompt() {
-	read -r -p "Continue? [Y/n] " response
-			case $response in
-				[yY])
-				echo "Resuming..."
-				;;
-				*)
-				echo ""
-				colecho "Installation stopped" $info
-				echo -ne $NORMAL
-				exit 0
-				;;
-			esac
-}
-
-##!!!! createdir_prompt() : Prompt to create a directory
-createdir_prompt() {
-read -r -p "Path [ex:/home/pi/]: " directory
-jumpline
-nlbecho "This will create"
-colecho "$directory" $ERR
-read -r -p "CONFIRM [Y/n/a] [Yes/No/Abort] : " confirmation
-case $confirmation in
-				[yY])
-				createdir $directory
-				;;
-				[aA])
-				error_box 1
-				echo "INSTALLATION ABORTED"
-				error_box 1
-				read
-				exit 0
-				;;
-				*)
-				jumpline
-				createdir_prompt
-				;;
-esac
-}
-
-##!!!! backup_prompt() : Prompt to create a backup of a file
-##>* $1 File to backup
-backup_prompt(){
-colecho "THIS WILL OVERWRITE $1 !" $ERR
-colecho "(A backup will be made at $1.backup.TIMESTAMP)" $WARN
-continue_prompt
-TIMESTAMP=$(date +%y%m%d)'_'$(date +%H%M%S)
-cp $1 $1'.backup.'$TIMESTAMP
-}
 
 #################
-##!!! Menu     
+## MENU         #
 #################
 
-##!!!! mainmenu() : Generate Main Menu
+# Generate Main Menu #
 mainmenu() {
 ping_test google.com
 
@@ -547,9 +566,9 @@ case $response in
 esac
 }
 
-##!!!! confmenu : Generate a Configuration Menu
-##>* $1 configuration repo in lazass/conf/
-##>* $2 configuration file to modify 
+# Generate a Configuration Menu #
+#$1 configuration repo in lazass/conf/
+#$2 configuration file to modify 
 confmenu() {
 	conf_dir=$1
 	conf_origin=$2
@@ -619,14 +638,4 @@ case $conf_file in
 				restarter $conf_dir
 				;;
 esac
-}
-
-display_gpio() {
-	line_break
-	echo "5V  5V  GND 15  16  1   GND 4   5   GND 6   10  11 "
-    echo "o   o   o   o   o   o   o   o   o   o   o   o   o  "
-    echo "o   o   o   o   o   o   o   o   o   o   o   o   o  "
-    echo "3V  8   9   7   GND 0   2   3   3V  12  13  14  GND"
-    colecho "P1" $OK
-    line_break
 }
